"""Baseline — schema as built by app/init_db.py.

This revision intentionally does nothing: it marks the point at which the
current (init_db-managed) schema is considered the Alembic baseline. Adopt it
on an existing database with ``alembic stamp 0001_baseline`` (or
``alembic stamp head``); every subsequent schema change should be a real
autogenerated migration on top of this one.

Revision ID: 0001_baseline
Revises:
Create Date: 2026-06-01
"""

revision = "0001_baseline"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # No-op: the schema already exists (created by db.create_all + init_db).
    pass


def downgrade() -> None:
    pass
